export const TrainingTask = {
    IMAGE_CLASSIFICATION: "IMAGE_CLASSIFICATION",
    TEXT_CLASSIFICATION: "TEXT_CLASSIFICATION",
    MULTILABEL_TEXT_CLASSIFICATION: "MULTILABEL_TEXT_CLASSIFICATION",
    TABULAR_CLASSIFICATION: "TABULAR_CLASSIFICATION",
    TABULAR_REGRESSION: "TABULAR_REGRESSION",
    MULTILABEL_TABULAR_CLASSIFICATION: "MULTILABEL_TABULAR_CLASSIFICATION",
    MULTIMODAL_CLASSIFICATION: "MULTIMODAL_CLASSIFICATION",
}