export const TrainingTask = {
    IMAGE_CLASSIFICATION: "IMAGE_CLASSIFICATION",
    TEXT_CLASSIFICATION: "TEXT_CLASSIFICATION",
    TABULAR_CLASSIFICATION: "TABULAR_CLASSIFICATION",
    MULTILABEL_TABULAR_CLASSIFICATION: "MULTILABEL_TABULAR_CLASSIFICATION",
    MULTIMODAL_CLASSIFICATION: "MULTIMODAL_CLASSIFICATION",
    TABULAR_REGRESSION: "TABULAR_REGRESSION",
    SEMANTIC_SEGMENTATION: "SEMANTIC_SEGMENTATION",
    TIME_SERIES: "TIME_SERIES",
    CLUSTERING: "CLUSTERING",
}